import Head from "next/head";
import Image from "next/image";
import Logo from "../public/Logo.svg";
import Illustration from "../public/Illustration.svg";
import Blob from "../public/Blob.svg";
import ModernWorkface from "../public/Icon-3.svg";
import Meritocratic from "../public/Icon-2.svg";
import Engineered from "../public/Icon.svg";
import KickStart from "../public/Icon-4.svg";
import Onboard from "../public/Icon.png";
import Engage from "../public/Icon2.png";
import Dillon from "../public/Dillon.svg";
import Anna from "../public/Anna.svg";
import Kas from "../public/Kas.svg";
import Jassir from "../public/Jassir.svg";
import Lizzie from "../public/cover2.svg";
import Jason from "../public/cover3.svg";
import Alex from "../public/cover.svg";
import Pablo from "../public/pablo.svg";
import { AiFillStar } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>Open Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="">
        <header className="flex justify-between ml-6 sm:ml-36 mt-8 align-middle">
          <div className="flex justify-center  ">
            <Image src={Logo} alt={"Logo Open Enterprise"} />
            <h1 className="text-4xl font-bold pl-2">Open Enterprise</h1>
          </div>
          <ul className="flex hidden sm:line-block gap-10 mr-10 mt-2 cursor-pointer">
            <li>Why Open Enterprise</li>
            <li>Features</li>
            <li>Contribute</li>
            <li className=" text-green">Request early acess</li>
          </ul>
        </header>
        <section className="sm:pt-20 pt-10 ml-6 flex flex-col sm:justify-between sm:flex-row h-4/5">
          <article className="sm:mt-40 mt-10 sm:ml-32 w-2/2">
            <h2 className=" font-bold text-2xl sm:text-5xl justify-center  leading-2">
              A new model for <br />
              open collaboration
            </h2>
            <p className="leading-2 mt-10 text-slate-700">
              Run an organization where members get rewarded for their
              contributions with fractional ownership.
            </p>
            <button className="text-white bg-green rounded mt-10 h-14 w-40 font-extralight  ">
              Request early acess
            </button>
          </article>
          <article className="sm:w-1/2 w-1/4">
            <div className="">
              <Image
                src={Illustration}
                alt={"Companheiros de trabalho se comprimentando"}
                height={600}
                width={800}
                className={"z-40 absolute hidden md:inline-block"}
              />
              <Image
                src={Blob}
                alt={"Poça de fundo"}
                width={600}
                className={
                  "z-30 float-right mr-30 h-8xl hidden md:inline-block"
                }
              />
            </div>
          </article>
        </section>
        <section className="sm:mt-40 mt-10 ml-4 sm:ml-36 h-auto flex flex-col">
          <h3 className=" font-bold text-2xl sm:text-5xl justify-center  leading-2">
            Reimagining what <br className="sm:hidden " />
            it means to work
          </h3>
          <p className="leading-8 mt-10 text-slate-700 h-60 sm:h-40 mx-auto">
            Teams and communities using Open Enterprise fundamentally unlock a
            reality of work that reimagines how people{" "}
            <br className="hidden sm:inline-block" />
            &nbsp; &nbsp; &nbsp; engage in economic opportunity, meeting the
            demands and expectations of a modern organization.
          </p>
          <article className="flex flex-col sm:flex-row justify-between mx-auto gap-10 pb-20 ">
            <div className="border  h-72 w-72 mx-auto shadow-md shadow-gray-500 border-none rounded-lg flex flex-col">
              <Image
                src={ModernWorkface}
                alt={"Logo modern"}
                className={"mx-auto h-20 w-20 mt-14"}
              />
              <h5 className=" font-medium mx-auto">Modern Workface</h5>
              <p className=" font-extralight text-slate-700 mx-auto p-4 mt-2">
                Multistakeholder governance aligns employees with the
                organization&apos;s wider community.
              </p>
            </div>
            <div className="border  h-72 w-72 mx-auto shadow-md shadow-gray-500 border-none rounded-lg flex flex-col">
              <Image
                src={Meritocratic}
                alt={"Logo modern"}
                className={"mx-auto h-20 w-20 mt-14"}
              />
              <h5 className=" font-medium mx-auto">Modern Workface</h5>
              <p className=" font-extralight text-slate-700 mx-auto p-4 mt-2">
                Tokenized ownership aligns deeply committed individuals with the
                organization’s success.
              </p>
            </div>
            <div className="border  h-72 w-72 mx-auto shadow-md shadow-gray-500 border-none rounded-lg flex flex-col">
              <Image
                src={Engineered}
                alt={"Logo modern"}
                className={"mx-auto h-20 w-20 mt-14"}
              />
              <h5 className=" font-medium mx-auto">Modern Workface</h5>
              <p className=" font-extralight text-slate-700 mx-auto p-4 mt-2">
                Open Enterprise supports best practices in sociocratic
                management.
              </p>
            </div>
          </article>
        </section>
        <section className="pb-0 sm:pb-0 h-80">
          <article className="flex justify-between ml-6 flex-col sm:flex-row h-screen sm:ml-36  sm:h-40">
            <div className="flex flex-col w-4/4">
              <Image
                src={KickStart}
                alt={"Icon Start"}
                className={" h-14 w-14"}
              />
              <h5 className="mt-8 font-bold text-2xl sm:text-5xl justify-center  leading-2 ">
                Kickstart an organization <br />
                with your co-founders
              </h5>
              <p className="mt-8 font-light leading-8">
                It’s the early days, you just had a long conversation with two
                friends about a <br className="hidden sm:inline-block" />{" "}
                meaningful challenge that you’re all passionate about and have a
                potential solution <br className="hidden sm:inline-block" />{" "}
                for. You’re ready to embark the startup journey.
              </p>
            </div>
            <div>
              <div className=" rounded-lg flex flex-col z-50 absolute h-80 w-64  shadow-green float-left border-gray-900 border-2">
                <p className="pl-10 pt-5 pb-5 text-2xl font-bold">Members</p>
                <div className="flex flex-col gap-6">
                  <div className="flex flex-row ml-10">
                    <Image
                      src={Dillon}
                      alt={"Dillon image"}
                      className={"rounded-full h-14 w-14"}
                    />
                    <div className="pl-4">
                      <p>Dillon Kydd</p>
                      <p className=" font-thin text-slate-500 text-sm">
                        100 SHARES
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-row ml-10">
                    <Image
                      src={Anna}
                      alt={"Dillon image"}
                      className={"rounded-full h-14 w-14"}
                    />
                    <div className="pl-4">
                      <p>Anna Olsen</p>
                      <p className=" font-thin text-slate-500 text-sm">
                        100 SHARES
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-row ml-10">
                    <Image
                      src={Kas}
                      alt={"Dillon image"}
                      className={"rounded-full h-14 w-14"}
                    />
                    <div className="pl-4">
                      <p>Kas Moss</p>
                      <p className=" font-thin text-slate-500 text-sm">
                        100 SHARES
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </article>
        </section>
        <section className="flex justify-between h-max mt-40 sm:mt-80 ml-6 sm:ml-32 sm:flex-row flex-col">
          <article className="mt-64">
            <div className="flex flex-col z-50  h-80 w-64   rounded-md  shadow-green float-left border-gray-900 border-2">
              <span className="p-5 flex flex-col">
                <div className="flex flex-row">
                  <Image
                    src={Jassir}
                    alt={"Image Jassir"}
                    className={"rounded"}
                  />
                  <legend className="pl-2">
                    <p className="font-medium tex-md leading-10">
                      Jassir Jonis
                    </p>
                    <p className="font-thin text-slate-500 text-sm leading-4">
                      Pre-seed angel investor
                    </p>
                  </legend>
                </div>
                <p className=" font-light text-slate-700 text-sm leading-4 mt-4">
                  Hey guys, love what you’re doing and I’m convinced that
                  together we’ll achieve amazing things.
                </p>
                <div className="flex flex-row mt-4 gap-10">
                  <legend className="">
                    <p className=" font-light text-slate-700 text-sm leading-8">
                      COMMIT
                    </p>
                    <p>10 , 000 DAI</p>
                  </legend>
                  <legend>
                    <p className=" font-light text-slate-700 text-sm leading-8">
                      SHARES
                    </p>
                    <p>20</p>
                  </legend>
                </div>
                <button className="text-white font-md bg-gray-900 border border-lg mt-4 rounded roundeg-lg h-10 w-30">
                  Go to vote
                </button>
              </span>
            </div>
          </article>
          <article className="flex flex-col mt-10 sm:mt-0 sm:w-3/5">
            <Image
              src={Onboard}
              alt={"Imagem de onboarding"}
              className={"h-20 w-20"}
            />
            <h5 className=" leading-10 font-bold text-3xl sm:text-5xl mt-10">
              Onboard users, investors <br />
              and advisors as you grow
            </h5>
            <p className="mt-10 font-thin sm:w-2/4 w-4/4 leading-6">
              You’ve bootstrapped and delivered an MVP, and some investors and
              advisors are interested in having a chat with you. As an Open
              Enterprise, you can onboard them seamlessly into your digital
              organization and align them with your success.
            </p>
          </article>
        </section>
        <section className="flex justify-between sm:mt-44 mt-20 sm:ml-32 ml-4 sm:flex-row flex-col ">
          <article className="flex flex-col mt-2">
            <Image src={Engage} alt={"Engage image"} />
            <h5 className=" leading-10 font-bold text-5xl mt-10">
              Engage highly committed contributors
            </h5>
            <p className="mt-10 font-thin w-4/4 leading-6">
              You need talented people on-demand across various tasks that your
              full-time workforce can’t prioritize at the moment. As an Open
              Enterprise, you can easily fund tasks and have people apply to
              work on them in return for funds or shares.
            </p>
          </article>
          <article className="flex flex-row w-4/5 sm:w-3/5  gap-12 flex-wrap">
            <aside className=" flex flex-col mt-10 sm:mt-0 w-12/12 sm:w-8/12  rounded-xl  shadow-green float-left border-gray-900 border-2">
              <div className="p-3">
                <p>Write how-to Open Enterprise</p>
                <p className="mt-2 font-thin w-3/4 leading-6 text-stone-600">
                  Looking for an amazing copywriter using <br />
                  Open Enterprise to help us write an article <br /> on how to
                  get started.
                </p>
              </div>
            </aside>
            <aside className=" flex flex-col w-96 sm:w-6/12  rounded-xl   border-gray-900 border-2">
              <div className="sm:p-10 p-4">
                <p className=" text-2xl">3 applicants</p>
                <div className="flex flex-row items-center gap-4 align-text-bottom justify-between ">
                  <Image
                    src={Jason}
                    alt={"Jason Profile Image"}
                    className={" rounded-full h-10 w-10 mt-4"}
                  />
                  <p className=" align-middle mt-4"> Jason Kwon </p>
                  <AiFillStar className=" fill-yellow-400 mt-4" />
                  <p className="mt-4">4.8</p>
                </div>
                <div className="flex flex-row items-center align-text-bottom justify-between">
                  <Image
                    src={Alex}
                    alt={"Alex Profile Image"}
                    className={" rounded-full h-10 w-10 mt-4"}
                  />
                  <p className=" align-middle mt-4"> Alex Rose </p>
                  <AiFillStar className=" fill-yellow-400 mt-4 ml-3" />
                  <p className="mt-4">4.5</p>
                </div>
                <div className="flex flex-row items-center gap-4 align-text-bottom justify-between">
                  <Image
                    src={Lizzie}
                    alt={"Lizzie Profile Image"}
                    className={" rounded-full h-10 w-10 mt-4"}
                  />
                  <p className=" align-middle mt-4"> Lizzie Ulrich </p>
                  <AiFillStar className=" fill-yellow-400 mt-4" />
                  <p className="mt-4">4.2</p>
                </div>
              </div>
            </aside>
            <aside className=" flex flex-col  sm:mt-12 w-10/12 sm:w-4/12  rounded-xl items-center gap-2 shadow-green float-left border-gray-900 border-2">
              <Image
                src={Alex}
                alt={"Alex Rose Profile"}
                className={" rounded-full h-14 w-14 mt-4"}
              />
              <p className="font-medium text-2xl ">Alex Rose</p>
              <p className="font-thin ">Ux Writer</p>
              <div className="flex flex-row items-center gap-4 ">
                <p>4 commits</p>
                <p>
                  <AiFillStar className=" fill-yellow-400" />
                </p>
                <p>4.5</p>
              </div>
              <button className=" bg-gray-800 text-white font-medium rounded-lg w-40 h-10 mb-4">
                View profile
              </button>
            </aside>
          </article>
        </section>
        <section className=" h-auto mt-40">
          <h2 className="text-center font-bold text-2xl sm:text-5xl">
            Help us improve Open Enterprise
          </h2>
          <p className="p-4 sm:text-center leading-8 mt-4 ml-6  font-thin">
            As an Open Enterprise ourselves, we are actively looking for new
            talent to join our mission of improving and delivering{" "}
            <br className="hidden sm:inline-block" /> the Open Enterprise model
            to the world. Apply for open tasks and earn a stake in our success.
          </p>
          <aside className="flex sm:flex-row flex-col sm:ml-36 ml-6 sm:gap-24">
            <div className=" flex flex-col  mt-12   rounded-xl items-center gap-2  sm:h-60 h-72 sm:w-96 w-72 border">
              <div className="p-8">
                <p className=" font-bold text-xl">
                  Ideate a list of features based on the Sociocracy model
                </p>
                <p className=" pb-4 pt-4 font-thin">
                  We’re looking for someone interested in business theory and
                  research that’ll help us bridge the gap between our s...
                </p>
                <div className="flex justify-between">
                  <p className="rounded-xl  bg-green text-white h-6 w-12 text-center">
                    5 Aut
                  </p>
                  <p>Apply by May 15</p>
                </div>
              </div>
            </div>
            <div className=" flex flex-col  mt-12   rounded-xl items-center gap-2  sm:h-60 h-72 sm:w-96 w-72 border">
              <div className="p-8">
                <p className=" font-bold text-xl">
                  Ideate a list of features based on the Sociocracy model
                </p>
                <p className=" pb-4 pt-4 font-thin">
                  We’re looking for someone interested in business theory and
                  research that’ll help us bridge the gap between our s...
                </p>
                <div className="flex justify-between">
                  <p className="rounded-xl  bg-green text-white h-6 w-12 text-center">
                    5 Aut
                  </p>
                  <p>Apply by May 15</p>
                </div>
              </div>
            </div>
            <div className=" flex flex-col  mt-12   rounded-xl items-center gap-2 sm:h-60 h-72 sm:w-96 w-72 border">
              <div className="p-8">
                <p className=" font-bold text-xl">
                  Ideate a list of features based on the Sociocracy model
                </p>
                <p className=" pb-4 pt-4 font-thin">
                  We’re looking for someone interested in business theory and
                  research that’ll help us bridge the gap between our s...
                </p>
                <div className="flex justify-between">
                  <p className="rounded-xl  bg-green text-white h-6 w-12 text-center">
                    5 Aut
                  </p>
                  <p>Apply by May 15</p>
                </div>
              </div>
            </div>
          </aside>
        </section>
        <section>
          <article className="flex  flex-col sm:flex-row mt-40 sm:ml-32 ml-6 justify-between">
            <div className="flex flex-col">
              <h3 className=" leading-10 font-bold text-5xl sm:mt-10 mt-4">
                Start an Open Enterprise
              </h3>
              <p className=" leading-6 mt-10">
                If you can’t wait to run a new or existing organization on Open
                Enterprise and are <br className="hidden sm:inline-block" />{" "}
                willing to explore and navigate the beta, we’d love to get you
                started.
              </p>
              <button className="w-40 mt-10 h-14 text-white bg-green rounded-lg">
                Requesy early acess
              </button>
            </div>
            <aside className="w-2/2 h-2/2 mt-10 sm:mt-0">
              <Image src={Pablo} alt={"Pablo image"} />
            </aside>
          </article>
        </section>
      </main>
    </>
  );
}
